// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtffYylV76e0nu9mLkp1ro3Rs8hfWAm8',
    appId: '1:1096393764737:web:d49bfcbf14102363548280',
    messagingSenderId: '1096393764737',
    projectId: 'deep-mind-ai-ba35a',
    authDomain: 'deep-mind-ai-ba35a.firebaseapp.com',
    storageBucket: 'deep-mind-ai-ba35a.firebasestorage.app',
    measurementId: 'G-C6EE0RPCL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB67Dv5DiE6fMFTt9f5ebh61oczHl2uZ9w',
    appId: '1:1096393764737:android:1ad5c6d9160f4526548280',
    messagingSenderId: '1096393764737',
    projectId: 'deep-mind-ai-ba35a',
    storageBucket: 'deep-mind-ai-ba35a.firebasestorage.app',
  );
}
